-- Dumbbell Exercises Seed File
-- System exercises for dumbbell training

INSERT INTO "ExerciseDefinition" (
  id,
  name,
  "normalizedName",
  aliases,
  category,
  "isSystem",
  "createdBy",
  "userId",
  equipment,
  "primaryFAUs",
  "secondaryFAUs",
  instructions,
  force,
  mechanic,
  level,
  "createdAt",
  "updatedAt"
) VALUES
-- Chest exercises
('ex_db_001', 'Incline Dumbbell Bench Press', 'incline dumbbell bench press', ARRAY['incline db bench', 'incline dumbbell press'], 'chest', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell', 'bench'], ARRAY['chest', 'triceps'], ARRAY['front-delts'], '1. Lie back on an incline bench with a dumbbell in each hand atop your thighs. The palms of your hands will be facing each other.
2. Then, using your thighs to help push the dumbbells up, lift the dumbbells one at a time so that you can hold them at shoulder width.
3. Once you have the dumbbells raised to shoulder width, rotate your wrists forward so that the palms of your hands are facing away from you. This will be your starting position.
4. Be sure to keep full control of the dumbbells at all times. Then breathe out and push the dumbbells up with your chest.
5. Lock your arms at the top, hold for a second, and then start slowly lowering the weight. Tip Ideally, lowering the weights should take about twice as long as raising them.
6. Repeat the movement for the prescribed amount of repetitions.
7. When you are done, place the dumbbells back on your thighs and then on the floor. This is the safest manner to release the dumbbells.', 'push', 'compound', 'beginner', NOW(), NOW()),
('ex_db_002', 'Decline Dumbbell Bench Press', 'decline dumbbell bench press', ARRAY['decline db bench', 'decline dumbbell press'], 'chest', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell', 'decline_bench'], ARRAY['chest', 'triceps'], ARRAY['front-delts'], '1. Secure your legs at the end of the decline bench and lie down with a dumbbell on each hand on top of your thighs. The palms of your hand will be facing each other.
2. Once you are laying down, move the dumbbells in front of you at shoulder width.
3. Once at shoulder width, rotate your wrists forward so that the palms of your hands are facing away from you. This will be your starting position.
4. Bring down the weights slowly to your side as you breathe out. Keep full control of the dumbbells at all times. Tip: Throughout the motion, the forearms should always be perpendicular to the floor.
5. As you breathe out, push the dumbbells up using your pectoral muscles. Lock your arms in the contracted position, squeeze your chest, hold for a second and then start coming down slowly. Tip: It should take at least twice as long to go down than to come up..
6. Repeat the movement for the prescribed amount of repetitions of your training program.', 'push', 'compound', 'beginner', NOW(), NOW()),
('ex_db_003', 'Dumbbell Fly', 'dumbbell fly', ARRAY['db fly', 'dumbbell flys', 'chest fly'], 'chest', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell', 'bench'], ARRAY['chest'], ARRAY['front-delts'], '1. Lie down on a flat bench with a dumbbell on each hand resting on top of your thighs. The palms of your hand will be facing each other.
2. Then using your thighs to help raise the dumbbells, lift the dumbbells one at a time so you can hold them in front of you at shoulder width with the palms of your hands facing each other. Raise the dumbbells up like you''re pressing them, but stop and hold just before you lock out. This will be your starting position.
3. With a slight bend on your elbows in order to prevent stress at the biceps tendon, lower your arms out at both sides in a wide arc until you feel a stretch on your chest. Breathe in as you perform this portion of the movement. Tip: Keep in mind that throughout the movement, the arms should remain stationary; the movement should only occur at the shoulder joint.
4. Return your arms back to the starting position as you squeeze your chest muscles and breathe out. Tip: Make sure to use the same arc of motion used to lower the weights.
5. Hold for a second at the contracted position and repeat the movement for the prescribed amount of repetitions.', 'push', 'isolation', 'beginner', NOW(), NOW()),
('ex_db_004', 'Incline Dumbbell Fly', 'incline dumbbell fly', ARRAY['incline db fly', 'incline chest fly'], 'chest', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell', 'bench'], ARRAY['chest'], ARRAY['front-delts'], '1. Hold a dumbbell on each hand and lie on an incline bench that is set to an incline angle of no more than 30 degrees.
2. Extend your arms above you with a slight bend at the elbows.
3. Now rotate the wrists so that the palms of your hands are facing you. Tip: The pinky fingers should be next to each other. This will be your starting position.
4. As you breathe in, start to slowly lower the arms to the side while keeping the arms extended and while rotating the wrists until the palms of the hand are facing each other. Tip: At the end of the movement the arms will be by your side with the palms facing the ceiling.
5. As you exhale start to bring the dumbbells back up to the starting position by reversing the motion and rotating the hands so that the pinky fingers are next to each other again. Tip: Keep in mind that the movement will only happen at the shoulder joint and at the wrist. There is no motion that happens at the elbow joint.
6. Repeat for the recommended amount of repetitions.', 'push', 'compound', 'beginner', NOW(), NOW()),
('ex_db_005', 'Dumbbell Pullover', 'dumbbell pullover', ARRAY['db pullover', 'pullover'], 'chest', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell', 'bench'], ARRAY['chest', 'lats'], ARRAY['triceps'], '1. Lie down on a flat bench with a dumbbell on each hand resting on top of your thighs. The palms of your hand will be facing each other.
2. Then using your thighs to help raise the dumbbells, lift the dumbbells one at a time so you can hold them in front of you at shoulder width with the palms of your hands facing each other. Raise the dumbbells up like you''re pressing them, but stop and hold just before you lock out. This will be your starting position.
3. With a slight bend on your elbows in order to prevent stress at the biceps tendon, lower your arms out at both sides in a wide arc until you feel a stretch on your chest. Breathe in as you perform this portion of the movement. Tip: Keep in mind that throughout the movement, the arms should remain stationary; the movement should only occur at the shoulder joint.
4. Return your arms back to the starting position as you squeeze your chest muscles and breathe out. Tip: Make sure to use the same arc of motion used to lower the weights.
5. Hold for a second at the contracted position and repeat the movement for the prescribed amount of repetitions.', 'push', 'isolation', 'beginner', NOW(), NOW()),

-- Shoulder exercises
('ex_db_006', 'Dumbbell Shoulder Press', 'dumbbell shoulder press', ARRAY['db shoulder press', 'seated db press', 'dumbbell press'], 'shoulders', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell', 'bench'], ARRAY['front-delts', 'triceps'], ARRAY['side-delts'], '1. While holding a dumbbell in each hand, sit on a military press bench or utility bench that has back support. Place the dumbbells upright on top of your thighs.
2. Now raise the dumbbells to shoulder height one at a time using your thighs to help propel them up into position.
3. Make sure to rotate your wrists so that the palms of your hands are facing forward. This is your starting position.
4. Now, exhale and push the dumbbells upward until they touch at the top.
5. Then, after a brief pause at the top contracted position, slowly lower the weights back down to the starting position while inhaling.
6. Repeat for the recommended amount of repetitions.', 'push', 'compound', 'intermediate', NOW(), NOW()),
('ex_db_007', 'Arnold Press', 'arnold press', ARRAY['arnold shoulder press', 'arnold dumbbell press'], 'shoulders', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell', 'bench'], ARRAY['front-delts', 'side-delts', 'triceps'], ARRAY['chest'], '1. Sit on an exercise bench with back support and hold two dumbbells in front of you at about upper chest level with your palms facing your body and your elbows bent. Tip: Your arms should be next to your torso. The starting position should look like the contracted portion of a dumbbell curl.
2. Now to perform the movement, raise the dumbbells as you rotate the palms of your hands until they are facing forward.
3. Continue lifting the dumbbells until your arms are extended above you in straight arm position. Breathe out as you perform this portion of the movement.
4. After a second pause at the top, begin to lower the dumbbells to the original position by rotating the palms of your hands towards you. Tip: The left arm will be rotated in a counter clockwise manner while the right one will be rotated clockwise. Breathe in as you perform this portion of the movement.
5. Repeat for the recommended amount of repetitions.', 'push', 'compound', 'intermediate', NOW(), NOW()),
('ex_db_008', 'Front Raise', 'front raise', ARRAY['dumbbell front raise', 'db front raise'], 'shoulders', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell'], ARRAY['front-delts'], ARRAY['chest'], '1. Pick a couple of dumbbells and stand with a straight torso and the dumbbells on front of your thighs at arms length with the palms of the hand facing your thighs. This will be your starting position.
2. While maintaining the torso stationary (no swinging), lift the left dumbbell to the front with a slight bend on the elbow and the palms of the hands always facing down. Continue to go up until you arm is slightly above parallel to the floor. Exhale as you execute this portion of the movement and pause for a second at the top. Inhale after the second pause.
3. Now lower the dumbbell back down slowly to the starting position as you simultaneously lift the right dumbbell.
4. Continue alternating in this fashion until all of the recommended amount of repetitions have been performed for each arm.', 'push', 'isolation', 'beginner', NOW(), NOW()),
('ex_db_009', 'Rear Delt Fly', 'rear delt fly', ARRAY['reverse fly', 'bent over fly', 'rear delt raise'], 'shoulders', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell'], ARRAY['rear-delts'], ARRAY['mid-back', 'traps'], '1. While holding a dumbbell in each hand, lay with your chest down on a flat bench.
2. Position the palms of the hands in a neutral manner (palms facing your torso) as you keep the arms extended with the elbows slightly bent. This will be your starting position.
3. Now raise the arms to the side until your elbows are at shoulder height and your arms are roughly parallel to the floor as you exhale. Tip: Maintain your arms perpendicular to the torso while keeping them extended throughout the movement. Also, keep the contraction at the top for a second.
4. Slowly lower the dumbbells to the starting position as you inhale.
5. Repeat for the recommended amount of repetitions and then switch to the other arm.', 'pull', 'isolation', 'intermediate', NOW(), NOW()),
('ex_db_010', 'Upright Row', 'upright row', ARRAY['dumbbell upright row', 'db upright row'], 'shoulders', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell'], ARRAY['side-delts', 'traps'], ARRAY['biceps'], '1. Grasp a dumbbell in each hand with a pronated (palms forward) grip that is slightly less than shoulder width. The dumbbells should be resting on top of your thighs. Your arms should be extended with a slight bend at the elbows and your back should be straight. This will be your starting position.
2. Use your side shoulders to lift the dumbbells as you exhale. The dumbbells should be close to the body as you move it up and the elbows should drive the motion. Continue to lift them until they nearly touch your chin. Tip: Your elbows should drive the motion. As you lift the dumbbells, your elbows should always be higher than your forearms. Also, keep your torso stationary and pause for a second at the top of the movement.
3. Lower the dumbbells back down slowly to the starting position. Inhale as you perform this portion of the movement.
4. Repeat for the recommended amount of repetitions.', 'pull', 'compound', 'beginner', NOW(), NOW()),

-- Back exercises
('ex_db_011', 'Single Arm Dumbbell Row', 'single arm dumbbell row', ARRAY['one arm db row', 'single arm row', 'one arm dumbbell row'], 'back', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell', 'bench'], ARRAY['lats', 'mid-back'], ARRAY['biceps', 'rear-delts'], '1. Choose a flat bench and place a dumbbell on each side of it.
2. Place the right leg on top of the end of the bench, bend your torso forward from the waist until your upper body is parallel to the floor, and place your right hand on the other end of the bench for support.
3. Use the left hand to pick up the dumbbell on the floor and hold the weight while keeping your lower back straight. The palm of the hand should be facing your torso. This will be your starting position.
4. Pull the resistance straight up to the side of your chest, keeping your upper arm close to your side and keeping the torso stationary. Breathe out as you perform this step. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. Also, make sure that the force is performed with the back muscles and not the arms. Finally, the upper torso should remain stationary and only the arms should move. The forearms should do no other work except for holding the dumbbell; therefore do not try to pull the dumbbell up using the forearms.
5. Lower the resistance straight down to the starting position. Breathe in as you perform this step.
6. Repeat the movement for the specified amount of repetitions.
7. Switch sides and repeat again with the other arm.', 'pull', 'compound', 'beginner', NOW(), NOW()),
('ex_db_012', 'Bent Over Dumbbell Row', 'bent over dumbbell row', ARRAY['bent over db row', 'two arm dumbbell row'], 'back', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell'], ARRAY['lats', 'mid-back'], ARRAY['biceps', 'rear-delts'], '1. With a dumbbell in each hand (palms facing your torso), bend your knees slightly and bring your torso forward by bending at the waist; as you bend make sure to keep your back straight until it is almost parallel to the floor. Tip: Make sure that you keep the head up. The weights should hang directly in front of you as your arms hang perpendicular to the floor and your torso. This is your starting position.
2. While keeping the torso stationary, lift the dumbbells to your side (as you breathe out), keeping the elbows close to the body (do not exert any force with the forearm other than holding the weights). On the top contracted position, squeeze the back muscles and hold for a second.
3. Slowly lower the weight again to the starting position as you inhale.
4. Repeat for the recommended amount of repetitions.', 'pull', 'compound', 'beginner', NOW(), NOW()),
('ex_db_013', 'Dumbbell Deadlift', 'dumbbell deadlift', ARRAY['db deadlift', 'dumbbell dl'], 'back', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell'], ARRAY['hamstrings', 'glutes', 'lower-back'], ARRAY['traps', 'forearms'], '1. Lie down on a flat bench with a dumbbell on each hand resting on top of your thighs. The palms of your hand will be facing each other.
2. Then using your thighs to help raise the dumbbells, lift the dumbbells one at a time so you can hold them in front of you at shoulder width with the palms of your hands facing each other. Raise the dumbbells up like you''re pressing them, but stop and hold just before you lock out. This will be your starting position.
3. With a slight bend on your elbows in order to prevent stress at the biceps tendon, lower your arms out at both sides in a wide arc until you feel a stretch on your chest. Breathe in as you perform this portion of the movement. Tip: Keep in mind that throughout the movement, the arms should remain stationary; the movement should only occur at the shoulder joint.
4. Return your arms back to the starting position as you squeeze your chest muscles and breathe out. Tip: Make sure to use the same arc of motion used to lower the weights.
5. Hold for a second at the contracted position and repeat the movement for the prescribed amount of repetitions.', 'push', 'isolation', 'beginner', NOW(), NOW()),
('ex_db_014', 'Dumbbell Romanian Deadlift', 'dumbbell romanian deadlift', ARRAY['db rdl', 'dumbbell rdl'], 'back', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell'], ARRAY['hamstrings', 'glutes'], ARRAY['lower-back', 'forearms'], '1. Put a barbell in front of you on the ground and grab it using a pronated (palms facing down) grip that a little wider than shoulder width. Tip: Depending on the weight used, you may need wrist wraps to perform the exercise and also a raised platform in order to allow for better range of motion.
2. Bend the knees slightly and keep the shins vertical, hips back and back straight. This will be your starting position.
3. Keeping your back and arms completely straight at all times, use your hips to lift the bar as you exhale. Tip: The movement should not be fast but steady and under control.
4. Once you are standing completely straight up, lower the bar by pushing the hips back, only slightly bending the knees, unlike when squatting. Tip: Take a deep breath at the start of the movement and keep your chest up. Hold your breath as you lower and exhale as you complete the movement.
5. Repeat for the recommended amount of repetitions.', 'pull', 'compound', 'intermediate', NOW(), NOW()),
('ex_db_015', 'Dumbbell Shrug', 'dumbbell shrug', ARRAY['db shrug', 'dumbbell shrugs'], 'back', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell'], ARRAY['traps'], ARRAY['forearms'], '1. Stand erect with a dumbbell on each hand (palms facing your torso), arms extended on the sides.
2. Lift the dumbbells by elevating the shoulders as high as possible while you exhale. Hold the contraction at the top for a second. Tip: The arms should remain extended at all times. Refrain from using the biceps to help lift the dumbbells. Only the shoulders should be moving up and down.
3. Lower the dumbbells back to the original position.
4. Repeat for the recommended amount of repetitions.', 'pull', 'isolation', 'beginner', NOW(), NOW()),

-- Arm exercises - Biceps
('ex_db_016', 'Dumbbell Curl', 'dumbbell curl', ARRAY['db curl', 'dumbbell curls', 'bicep curl'], 'arms', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell'], ARRAY['biceps'], ARRAY['forearms'], '1. Stand up straight with a dumbbell in each hand at arm''s length. Keep your elbows close to your torso and rotate the palms of your hands until they are facing forward. This will be your starting position.
2. Now, keeping the upper arms stationary, exhale and curl the weights while contracting your biceps. Continue to raise the weights until your biceps are fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a brief pause as you squeeze your biceps.
3. Then, inhale and slowly begin to lower the dumbbells back to the starting position.
4. Repeat for the recommended amount of repetitions.', 'pull', 'isolation', 'beginner', NOW(), NOW()),
('ex_db_017', 'Alternating Dumbbell Curl', 'alternating dumbbell curl', ARRAY['alternating db curl', 'alternate dumbbell curl'], 'arms', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell'], ARRAY['biceps'], ARRAY['forearms'], '1. Sit down on an incline bench with a dumbbell in each hand being held at arms length. Tip: Keep the elbows close to the torso.This will be your starting position.
2. While holding the upper arm stationary, curl the right weight forward while contracting the biceps as you breathe out. As you do so, rotate the hand so that the palm is facing up. Continue the movement until your biceps is fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a second as you squeeze the biceps. Tip: Only the forearms should move.
3. Slowly begin to bring the dumbbell back to starting position as your breathe in.
4. Repeat the movement with the left hand. This equals one repetition.
5. Continue alternating in this manner for the recommended amount of repetitions.', 'pull', 'isolation', 'beginner', NOW(), NOW()),
('ex_db_018', 'Incline Dumbbell Curl', 'incline dumbbell curl', ARRAY['incline db curl', 'incline bicep curl'], 'arms', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell', 'bench'], ARRAY['biceps'], ARRAY['forearms'], '1. Sit back on an incline bench with a dumbbell in each hand held at arms length. Keep your elbows close to your torso and rotate the palms of your hands until they are facing forward. This will be your starting position.
2. While holding the upper arm stationary, curl the weights forward while contracting the biceps as you breathe out. Only the forearms should move. Continue the movement until your biceps are fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a second.
3. Slowly begin to bring the dumbbells back to starting position as your breathe in.
4. Repeat for the recommended amount of repetitions.', 'pull', 'isolation', 'beginner', NOW(), NOW()),
('ex_db_019', 'Concentration Curl', 'concentration curl', ARRAY['seated concentration curl', 'dumbbell concentration curl'], 'arms', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell', 'bench'], ARRAY['biceps'], ARRAY['forearms'], '1. Sit down on a flat bench with one dumbbell in front of you between your legs. Your legs should be spread with your knees bent and feet on the floor.
2. Use your right arm to pick the dumbbell up. Place the back of your right upper arm on the top of your inner right thigh. Rotate the palm of your hand until it is facing forward away from your thigh. Tip: Your arm should be extended and the dumbbell should be above the floor. This will be your starting position.
3. While holding the upper arm stationary, curl the weights forward while contracting the biceps as you breathe out. Only the forearms should move. Continue the movement until your biceps are fully contracted and the dumbbells are at shoulder level. Tip: At the top of the movement make sure that the little finger of your arm is higher than your thumb. This guarantees a good contraction. Hold the contracted position for a second as you squeeze the biceps.
4. Slowly begin to bring the dumbbells back to starting position as your breathe in. Caution: Avoid swinging motions at any time.
5. Repeat for the recommended amount of repetitions. Then repeat the movement with the left arm.', 'pull', 'isolation', 'beginner', NOW(), NOW()),
('ex_db_020', 'Preacher Curl', 'preacher curl', ARRAY['dumbbell preacher curl', 'db preacher curl'], 'arms', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell', 'preacher_bench'], ARRAY['biceps'], ARRAY['forearms'], '1. To perform this movement you will need a preacher bench and an E-Z bar. Grab the E-Z curl bar at the close inner handle (either have someone hand you the bar which is preferable or grab the bar from the front bar rest provided by most preacher benches). The palm of your hands should be facing forward and they should be slightly tilted inwards due to the shape of the bar.
2. With the upper arms positioned against the preacher bench pad and the chest against it, hold the E-Z Curl Bar at shoulder length. This will be your starting position.
3. As you breathe in, slowly lower the bar until your upper arm is extended and the biceps is fully stretched.
4. As you exhale, use the biceps to curl the weight up until your biceps is fully contracted and the bar is at shoulder height. Squeeze the biceps hard and hold this position for a second.
5. Repeat for the recommended amount of repetitions.', 'pull', 'isolation', 'beginner', NOW(), NOW()),
('ex_db_021', 'Spider Curl', 'spider curl', ARRAY['spider curls', 'incline spider curl'], 'arms', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell', 'bench'], ARRAY['biceps'], ARRAY['forearms'], '1. Start out by setting the bar on the part of the preacher bench that you would normally sit on. Make sure to align the barbell properly so that it is balanced and will not fall off.
2. Move to the front side of the preacher bench (the part where the arms usually lay) and position yourself to lay at a 45 degree slant with your torso and stomach pressed against the front side of the preacher bench.
3. Make sure that your feet (especially the toes) are well positioned on the floor and place your upper arms on top of the pad located on the inside part of the preacher bench.
4. Use your arms to grab the barbell with a supinated grip (palms facing up) at about shoulder width apart or slightly closer from each other.
5. Slowly begin to lift the barbell upwards and exhale. Hold the contracted position for a second as you squeeze the biceps.
6. Slowly begin to bring the barbell back to the starting position as your breathe in. .
7. Repeat for the recommended amount of repetitions.', 'pull', 'isolation', 'beginner', NOW(), NOW()),
('ex_db_022', 'Zottman Curl', 'zottman curl', ARRAY['zottman curls'], 'arms', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell'], ARRAY['biceps', 'forearms'], ARRAY[]::text[], '1. Stand up with your torso upright and a dumbbell in each hand being held at arms length. The elbows should be close to the torso.
2. Make sure the palms of the hands are facing each other. This will be your starting position.
3. While holding the upper arm stationary, curl the weights while contracting the biceps as you breathe out. Only the forearms should move. Your wrist should rotate so that you have a supinated (palms up) grip. Continue the movement until your biceps are fully contracted and the dumbbells are at shoulder level.
4. Hold the contracted position for a second as you squeeze the biceps.
5. Now during the contracted position, rotate your wrist until you now have a pronated (palms facing down) grip with the thumb at a higher position than the pinky.
6. Slowly begin to bring the dumbbells back down using the pronated grip.
7. As the dumbbells close your thighs, start rotating the wrist so that you go back to a neutral (palms facing your body) grip.
8. Repeat for the recommended amount of repetitions.', 'pull', 'isolation', 'intermediate', NOW(), NOW()),

-- Arm exercises - Triceps
('ex_db_023', 'Dumbbell Overhead Tricep Extension', 'dumbbell overhead tricep extension', ARRAY['overhead db extension', 'dumbbell tricep extension', 'two arm overhead extension'], 'arms', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell'], ARRAY['triceps'], ARRAY[]::text[], '1. Lie on a flat bench while holding two dumbbells directly in front of you. Your arms should be fully extended at a 90-degree angle from your torso and the floor. The palms should be facing in and the elbows should be tucked in. This is the starting position.
2. As you breathe in and you keep the upper arms stationary with the elbows in, slowly lower the weight until the dumbbells are near your ears.
3. At that point, while keeping the elbows in and the upper arms stationary, use the triceps to bring the weight back up to the starting position as you breathe out.
4. Repeat for the recommended amount of repetitions.', 'push', 'isolation', 'intermediate', NOW(), NOW()),
('ex_db_024', 'Single Arm Overhead Tricep Extension', 'single arm overhead tricep extension', ARRAY['one arm overhead extension', 'single arm db extension'], 'arms', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell'], ARRAY['triceps'], ARRAY[]::text[], '1. Attach dual handles to a sled using a chain or rope. Load the sled to an appropriate load.
2. Facing away from the sled, step away until there is tension in the line. Raise your hands above your head, keeping them together, palms facing each other. Your elbows should be pointed upward with the elbows flexed. This will be your starting position.
3. Extend through the elbow to straighten the arm. Ensure that your upper arm stays in position to isolate the triceps.
4. Upon full extension, step forward to take the slack out of the line. You may keep your feet staggered for more stability.', 'push', 'isolation', 'beginner', NOW(), NOW()),
('ex_db_025', 'Dumbbell Tricep Kickback', 'dumbbell tricep kickback', ARRAY['tricep kickback', 'db kickback'], 'arms', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell'], ARRAY['triceps'], ARRAY[]::text[], '1. Start with a dumbbell in each hand and your palms facing your torso. Keep your back straight with a slight bend in the knees and bend forward at the waist. Your torso should be almost parallel to the floor. Make sure to keep your head up. Your upper arms should be close to your torso and parallel to the floor. Your forearms should be pointed towards the floor as you hold the weights. There should be a 90-degree angle formed between your forearm and upper arm. This is your starting position.
2. Now, while keeping your upper arms stationary, exhale and use your triceps to lift the weights until the arm is fully extended. Focus on moving the forearm.
3. After a brief pause at the top contraction, inhale and slowly lower the dumbbells back down to the starting position.
4. Repeat the movement for the prescribed amount of repetitions.', 'push', 'isolation', 'beginner', NOW(), NOW()),
('ex_db_026', 'Tate Press', 'tate press', ARRAY['tate db press'], 'arms', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell', 'bench'], ARRAY['triceps'], ARRAY['chest'], '1. Lie down on a flat bench with a dumbbell in each hand on top of your thighs. The palms of your hand will be facing each other.
2. By using your thighs to help you get the dumbbells up, clean the dumbbells one arm at a time so that you can hold them in front of you at shoulder width. Note: when holding the dumbbells in front of you, make sure your arms are wider than shoulder width apart from each other using a pronated (palms forward) grip. Allow your elbows to point out. This is your starting position.
3. Keeping the upper arms stationary, slowly move the dumbbells in and down in a semi circular motion until they touch the upper chest while inhaling. Keep full control of the dumbbells at all times and do not move the upper arms nor rest the dumbbells on the chest.
4. As you breathe out, move the dumbbells up using your triceps and the same semi-circular motion but in reverse. Attempt to keep the dumbbells together as they move up. Lock your arms in the contracted position, hold for a second and then start coming down again slowly again. Tip: It should take at least twice as long to go down than to come up.
5. Repeat the movement for the prescribed amount of repetitions of your training program.', 'push', 'isolation', 'intermediate', NOW(), NOW()),
('ex_db_027', 'Dumbbell Skull Crusher', 'dumbbell skull crusher', ARRAY['db skull crusher', 'lying tricep extension'], 'arms', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell', 'bench'], ARRAY['triceps'], ARRAY[]::text[], '1. Lie on a flat bench and grasp the straight bar attachment of a low pulley with a narrow overhand grip. Tip: The easiest way to do this is to have someone hand you the bar as you lay down.
2. With your arms extended, position the bar over your torso. Your arms and your torso should create a 90-degree angle. This will be your starting position.
3. Lower the bar by bending at the elbow while keeping the upper arms stationary and elbows in. Go down until the bar lightly touches your forehead. Breathe in as you perform this portion of the movement.
4. Flex the triceps as you lift the bar back to its starting position. Exhale as you perform this portion of the movement.
5. Hold for a second at the contracted position and repeat for the recommended amount of repetitions.', 'push', 'isolation', 'beginner', NOW(), NOW()),

-- Leg exercises
('ex_db_028', 'Dumbbell Goblet Squat', 'dumbbell goblet squat', ARRAY['goblet squat', 'db goblet squat'], 'legs', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell'], ARRAY['quads', 'glutes'], ARRAY['abs'], '1. Stand holding a light kettlebell by the horns close to your chest. This will be your starting position.
2. Squat down between your legs until your hamstrings are on your calves. Keep your chest and head up and your back straight.
3. At the bottom position, pause and use your elbows to push your knees out. Return to the starting position, and repeat for 10-20 repetitions.', 'push', 'compound', 'beginner', NOW(), NOW()),
('ex_db_029', 'Dumbbell Front Squat', 'dumbbell front squat', ARRAY['db front squat'], 'legs', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell'], ARRAY['quads', 'glutes'], ARRAY['abs'], null, null, null, null, NOW(), NOW()),
('ex_db_030', 'Dumbbell Sumo Squat', 'dumbbell sumo squat', ARRAY['db sumo squat', 'sumo goblet squat'], 'legs', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell'], ARRAY['quads', 'glutes', 'adductors'], ARRAY['hamstrings'], null, null, null, null, NOW(), NOW()),
('ex_db_031', 'Dumbbell Bulgarian Split Squat', 'dumbbell bulgarian split squat', ARRAY['db bulgarian split squat'], 'legs', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell', 'bench'], ARRAY['quads', 'glutes'], ARRAY['hamstrings', 'abs'], '1. Stand up straight while holding a barbell placed on the back of your shoulders (slightly below the neck). Your feet should be placed wide apart with the foot of the lead leg angled out to the side. This will be your starting position.
2. Lower your body towards the side of your angled foot by bending the knee and hip of your lead leg and while keeping the opposite leg only slightly bent. Breathe in as you lower your body.
3. Return to the starting position by extending the hip and knee of the lead leg. Breathe out as you perform this movement.
4. After performing the recommended amount of reps, repeat the movement with the opposite leg.', 'push', 'compound', 'beginner', NOW(), NOW()),
('ex_db_032', 'Dumbbell Lunge', 'dumbbell lunge', ARRAY['db lunge', 'dumbbell forward lunge'], 'legs', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell'], ARRAY['quads', 'glutes'], ARRAY['hamstrings', 'abs'], '1. Stand with your torso upright holding two dumbbells in your hands by your sides. This will be your starting position.
2. Step forward with your right leg around 2 feet or so from the foot being left stationary behind and lower your upper body down, while keeping the torso upright and maintaining balance. Inhale as you go down. Note: As in the other exercises, do not allow your knee to go forward beyond your toes as you come down, as this will put undue stress on the knee joint. Make sure that you keep your front shin perpendicular to the ground.
3. Using mainly the heel of your foot, push up and go back to the starting position as you exhale.
4. Repeat the movement for the recommended amount of repetitions and then perform with the left leg.', 'push', 'compound', 'beginner', NOW(), NOW()),
('ex_db_033', 'Dumbbell Reverse Lunge', 'dumbbell reverse lunge', ARRAY['db reverse lunge'], 'legs', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell'], ARRAY['quads', 'glutes'], ARRAY['hamstrings', 'abs'], '1. Stand with your torso upright holding two dumbbells in your hands by your sides. This will be your starting position.
2. Step backward with your right leg around two feet or so from the left foot and lower your upper body down, while keeping the torso upright and maintaining balance. Inhale as you go down. Tip: As in the other exercises, do not allow your knee to go forward beyond your toes as you come down, as this will put undue stress on the knee joint. Make sure that you keep your front shin perpendicular to the ground. Keep the torso upright during the lunge; flexible hip flexors are important. A long lunge emphasizes the Gluteus Maximus; a short lunge emphasizes Quadriceps.
3. Push up and go back to the starting position as you exhale. Tip: Use the ball of your feet to push in order to accentuate the quadriceps. To focus on the glutes, press with your heels.
4. Now repeat with the opposite leg.', 'push', 'compound', 'intermediate', NOW(), NOW()),
('ex_db_034', 'Dumbbell Walking Lunge', 'dumbbell walking lunge', ARRAY['db walking lunge'], 'legs', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell'], ARRAY['quads', 'glutes'], ARRAY['hamstrings', 'abs'], null, null, null, null, NOW(), NOW()),
('ex_db_035', 'Dumbbell Step-Up', 'dumbbell step-up', ARRAY['db step up', 'dumbbell step up'], 'legs', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell', 'bench'], ARRAY['quads', 'glutes'], ARRAY['hamstrings'], '1. Stand up straight while holding a dumbbell on each hand (palms facing the side of your legs).
2. Place the right foot on the elevated platform. Step on the platform by extending the hip and the knee of your right leg. Use the heel mainly to lift the rest of your body up and place the foot of the left leg on the platform as well. Breathe out as you execute the force required to come up.
3. Step down with the left leg by flexing the hip and knee of the right leg as you inhale. Return to the original standing position by placing the right foot of to next to the left foot on the initial position.
4. Repeat with the right leg for the recommended amount of repetitions and then perform with the left leg.', 'push', 'compound', 'intermediate', NOW(), NOW()),
('ex_db_036', 'Dumbbell Calf Raise', 'dumbbell calf raise', ARRAY['db calf raise', 'dumbbell calf raises'], 'legs', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell'], ARRAY['calves'], ARRAY[]::text[], '1. Stand with your torso upright holding two dumbbells in your hands by your sides. Place the ball of the foot on a sturdy and stable wooden board (that is around 2-3 inches tall) while your heels extend off and touch the floor. This will be your starting position.
2. With the toes pointing either straight (to hit all parts equally), inwards (for emphasis on the outer head) or outwards (for emphasis on the inner head), raise the heels off the floor as you exhale by contracting the calves. Hold the top contraction for a second.
3. As you inhale, go back to the starting position by slowly lowering the heels.
4. Repeat for the recommended amount of times.', 'push', 'isolation', 'intermediate', NOW(), NOW()),

-- Glute exercises
('ex_db_037', 'Dumbbell Hip Thrust', 'dumbbell hip thrust', ARRAY['db hip thrust'], 'legs', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell', 'bench'], ARRAY['glutes', 'hamstrings'], ARRAY['lower-back'], null, null, null, null, NOW(), NOW()),
('ex_db_038', 'Dumbbell Single Leg Deadlift', 'dumbbell single leg deadlift', ARRAY['db single leg deadlift', 'single leg rdl'], 'legs', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell'], ARRAY['hamstrings', 'glutes'], ARRAY['lower-back', 'abs'], null, null, null, null, NOW(), NOW()),
('ex_db_039', 'Dumbbell Stiff Leg Deadlift', 'dumbbell stiff leg deadlift', ARRAY['db stiff leg deadlift', 'dumbbell sldl'], 'legs', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell'], ARRAY['hamstrings', 'glutes'], ARRAY['lower-back'], '1. Lie down on a flat bench with a dumbbell on each hand resting on top of your thighs. The palms of your hand will be facing each other.
2. Then using your thighs to help raise the dumbbells, lift the dumbbells one at a time so you can hold them in front of you at shoulder width with the palms of your hands facing each other. Raise the dumbbells up like you''re pressing them, but stop and hold just before you lock out. This will be your starting position.
3. With a slight bend on your elbows in order to prevent stress at the biceps tendon, lower your arms out at both sides in a wide arc until you feel a stretch on your chest. Breathe in as you perform this portion of the movement. Tip: Keep in mind that throughout the movement, the arms should remain stationary; the movement should only occur at the shoulder joint.
4. Return your arms back to the starting position as you squeeze your chest muscles and breathe out. Tip: Make sure to use the same arc of motion used to lower the weights.
5. Hold for a second at the contracted position and repeat the movement for the prescribed amount of repetitions.', 'push', 'isolation', 'beginner', NOW(), NOW()),

-- Core exercises
('ex_db_040', 'Dumbbell Side Bend', 'dumbbell side bend', ARRAY['db side bend', 'side bends'], 'core', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell'], ARRAY['obliques'], ARRAY[]::text[], '1. Stand up straight while holding a dumbbell on the left hand (palms facing the torso) as you have the right hand holding your waist. Your feet should be placed at shoulder width. This will be your starting position.
2. While keeping your back straight and your head up, bend only at the waist to the right as far as possible. Breathe in as you bend to the side. Then hold for a second and come back up to the starting position as you exhale. Tip: Keep the rest of the body stationary.
3. Now repeat the movement but bending to the left instead. Hold for a second and come back to the starting position.
4. Repeat for the recommended amount of repetitions and then change hands.', 'pull', 'isolation', 'beginner', NOW(), NOW()),
('ex_db_041', 'Dumbbell Russian Twist', 'dumbbell russian twist', ARRAY['db russian twist', 'weighted russian twist'], 'core', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell'], ARRAY['obliques', 'abs'], ARRAY[]::text[], '1. Lie down on the floor placing your feet either under something that will not move or by having a partner hold them. Your legs should be bent at the knees.
2. Elevate your upper body so that it creates an imaginary V-shape with your thighs. Your arms should be fully extended in front of you perpendicular to your torso and with the hands clasped. This is the starting position.
3. Twist your torso to the right side until your arms are parallel with the floor while breathing out.
4. Hold the contraction for a second and move back to the starting position while breathing out. Now move to the opposite side performing the same techniques you applied to the right side.
5. Repeat for the recommended amount of repetitions.', 'pull', 'compound', 'intermediate', NOW(), NOW()),
('ex_db_042', 'Dumbbell Woodchop', 'dumbbell woodchop', ARRAY['db woodchop', 'wood chop'], 'core', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell'], ARRAY['obliques'], ARRAY['front-delts'], null, null, null, null, NOW(), NOW()),

-- Forearm exercises
('ex_db_043', 'Dumbbell Wrist Curl', 'dumbbell wrist curl', ARRAY['db wrist curl', 'wrist curls'], 'arms', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell'], ARRAY['forearms'], ARRAY[]::text[], '1. Start out by placing a flat bench in front of a low pulley cable that has a straight bar attachment.
2. Use your arms to grab the cable bar with a narrow to shoulder width supinated grip (palms up) and bring them up so that your forearms are resting against the top of your thighs. Your wrists should be hanging just beyond your knees.
3. Start out by curling your wrist upwards and exhaling. Keep the contraction for a second.
4. Slowly lower your wrists back down to the starting position while inhaling.
5. Your forearms should be stationary as your wrist is the only movement needed to perform this exercise.
6. Repeat for the recommended amount of repetitions.', 'pull', 'isolation', 'beginner', NOW(), NOW()),
('ex_db_044', 'Dumbbell Reverse Wrist Curl', 'dumbbell reverse wrist curl', ARRAY['db reverse wrist curl', 'reverse wrist curls'], 'arms', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell'], ARRAY['forearms'], ARRAY[]::text[], '1. Stand up with your torso upright while holding a bar attachment that is attached to a low pulley using a pronated (palms down) and shoulder width grip. Make sure also that you keep the elbows close to the torso. This will be your starting position.
2. While holding the upper arms stationary, curl the weights while contracting the biceps as you breathe out. Only the forearms should move. Continue the movement until your biceps are fully contracted and the bar is at shoulder level. Hold the contracted position for a second as you squeeze the muscle.
3. Slowly begin to bring the bar back to starting position as your breathe in.
4. Repeat for the recommended amount of repetitions.', 'pull', 'isolation', 'beginner', NOW(), NOW()),
('ex_db_045', 'Farmer Walk', 'farmer walk', ARRAY['farmers walk', 'farmer carry', 'farmers carry'], 'full body', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell'], ARRAY['forearms', 'traps'], ARRAY['abs', 'calves'], '1. There are various implements that can be used for the farmers walk. These can also be performed with heavy dumbbells or short bars if these implements aren''t available. Begin by standing between the implements.
2. After gripping the handles, lift them up by driving through your heels, keeping your back straight and your head up.
3. Walk taking short, quick steps, and don''t forget to breathe. Move for a given distance, typically 50-100 feet, as fast as possible.', null, 'compound', 'intermediate', NOW(), NOW()),

-- Full body
('ex_db_046', 'Dumbbell Thruster', 'dumbbell thruster', ARRAY['db thruster', 'dumbbell squat press'], 'full body', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell'], ARRAY['quads', 'front-delts'], ARRAY['glutes', 'triceps', 'abs'], '1. Stand up straight while holding a dumbbell on each hand (palms facing the side of your legs).
2. Position your legs using a shoulder width medium stance with the toes slightly pointed out. Keep your head up at all times as looking down will get you off balance and also maintain a straight back. This will be your starting position. Note: For the purposes of this discussion we will use the medium stance described above which targets overall development; however you can choose any of the three stances discussed in the foot stances section.
3. Begin to slowly lower your torso by bending the knees as you maintain a straight posture with the head up. Continue down until your thighs are parallel to the floor. Tip: If you performed the exercise correctly, the front of the knees should make an imaginary straight line with the toes that is perpendicular to the front. If your knees are past that imaginary line (if they are past your toes) then you are placing undue stress on the knee and the exercise has been performed incorrectly.
4. Begin to raise your torso as you exhale by pushing the floor with the heel of your foot mainly as you straighten the legs again and go back to the starting position.
5. Repeat for the recommended amount of repetitions.', 'push', 'compound', 'beginner', NOW(), NOW()),
('ex_db_047', 'Dumbbell Snatch', 'dumbbell snatch', ARRAY['db snatch', 'single arm snatch'], 'full body', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell'], ARRAY['front-delts', 'glutes', 'hamstrings'], ARRAY['traps', 'abs', 'triceps'], null, null, null, null, NOW(), NOW()),
('ex_db_048', 'Dumbbell Clean', 'dumbbell clean', ARRAY['db clean', 'dumbbell hang clean'], 'full body', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell'], ARRAY['hamstrings', 'glutes', 'front-delts'], ARRAY['traps', 'abs'], '1. Begin standing with a dumbbell in each hand with your feet shoulder width apart.
2. Lower the weights to the floor by flexing at the hips and knees, pushing your hips back until the dumbbells reach the floor. This will be your starting position.
3. To initiate the movement, violently jump upward by extending the hips, knees, and ankles to acclerate the weights upward. Maintaining a neutral grip on the dumbbells, keep the arms straight until full extension is reached.
4. After full extension, rebend the hips and knees to receive the weight in a squat position. Allow the arms to bend, guiding the dumbbells to your shoulders.
5. Upon receiving the weight in the squat position, extend the hips and knees to finish in a standing position with the weights on your shoulders.', 'pull', 'compound', 'intermediate', NOW(), NOW()),
('ex_db_049', 'Dumbbell Clean and Press', 'dumbbell clean and press', ARRAY['db clean and press'], 'full body', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell'], ARRAY['front-delts', 'hamstrings', 'glutes'], ARRAY['traps', 'triceps', 'abs'], '1. Assume a shoulder-width stance, with knees inside the arms. Now while keeping the back flat, bend at the knees and hips so that you can grab the bar with the arms fully extended and a pronated grip that is slightly wider than shoulder width. Point the elbows out to sides. The bar should be close to the shins. Position the shoulders over or slightly ahead of the bar. Establish a flat back posture. This will be your starting position.
2. Begin to pull the bar by extending the knees. Move your hips forward and raise the shoulders at the same rate while keeping the angle of the back constant; continue to lift the bar straight up while keeping it close to your body.
3. As the bar passes the knee, extend at the ankles, knees, and hips forcefully, similar to a jumping motion. As you do so, continue to guide the bar with your hands, shrugging your shoulders and using the momentum from your movement to pull the bar as high as possible. The bar should travel close to your body, and you should keep your elbows out.
4. At maximum elevation, your feet should clear the floor and you should start to pull yourself under the bar. The mechanics of this could change slightly, depending on the weight used. You should descend into a squatting position as you pull yourself under the bar.
5. As the bar hits terminal height, rotate your elbows around and under the bar. Rack the bar across the front of the shoulders while keeping the torso erect and flexing the hips and knees to absorb the weight of the bar.
6. Stand to full height, holding the bar in the clean position.
7. Without moving your feet, press the bar overhead as you exhale. Lower the bar under control .', 'push', 'compound', 'intermediate', NOW(), NOW()),
('ex_db_050', 'Man Maker', 'man maker', ARRAY['manmaker', 'dumbbell man maker'], 'full body', true, null, '00000000-0000-0000-0000-000000000000', ARRAY['dumbbell'], ARRAY['chest', 'front-delts', 'quads', 'lats'], ARRAY['triceps', 'abs'], null, null, null, null, NOW(), NOW())
ON CONFLICT ("normalizedName") DO NOTHING;
