/** Boilerplate articles for the "Getting Started" learning collection */
export const DEV_ARTICLES = [
  {
    title: 'How to Read Your Program',
    slug: 'how-to-read-your-program',
    body: [
      '# How to Read Your Program',
      '',
      'Your program is organized into **weeks**, and each week contains **workouts** (training days).',
      '',
      '## What You\'ll See',
      '',
      'Each workout lists exercises with **prescribed sets**. For example:',
      '',
      '- **Barbell Bench Press**: 4 x 5 @ 155 lbs (RIR 3)',
      '',
      'This means 4 sets of 5 reps at 155 lbs, leaving about 3 reps in reserve.',
      '',
      '## Sets and Reps',
      '',
      '- **Sets**: How many rounds of the exercise',
      '- **Reps**: How many times you lift the weight per set',
      '- **RIR**: Reps In Reserve — how many more reps you *could* have done',
      '- **RPE**: Rate of Perceived Exertion (1-10 scale, 10 = maximum effort)',
      '',
      '## Logging Your Workout',
      '',
      'When you complete a workout, log what you actually did. This builds your training history.',
    ].join('\n'),
    level: 'beginner' as const,
    readTimeMinutes: 3,
  },
  {
    title: 'Understanding Progressive Overload',
    slug: 'understanding-progressive-overload',
    body: [
      '# Understanding Progressive Overload',
      '',
      'Progressive overload is the gradual increase of stress placed on the body during training.',
      '',
      '## How to Apply It',
      '',
      '1. **Add weight** — Add 5 lbs to the bar each week.',
      '2. **Add reps** — If you hit 3x8, try 3x9 next session before adding weight.',
      '3. **Add sets** — Go from 3 sets to 4 sets of the same weight and reps.',
      '',
      '## When to Progress',
      '',
      'Progress when you hit all prescribed reps with your target RIR.',
      '',
      '## Deloads',
      '',
      'Every 4-6 weeks, reduce volume or intensity by ~40% for a recovery week.',
    ].join('\n'),
    level: 'beginner' as const,
    readTimeMinutes: 4,
  },
  {
    title: 'Warming Up Effectively',
    slug: 'warming-up-effectively',
    body: [
      '# Warming Up Effectively',
      '',
      'A good warm-up primes your body for heavy work and reduces injury risk.',
      '',
      '## General Warm-Up (5 minutes)',
      '',
      '- Light cardio: walking, bike, or rowing',
      '- Dynamic stretches: leg swings, arm circles, hip circles',
      '',
      '## Exercise-Specific Warm-Up',
      '',
      '| Set | Weight | Reps |',
      '|-----|--------|------|',
      '| 1 | Empty bar | 10 |',
      '| 2 | 50% working weight | 5 |',
      '| 3 | 75% working weight | 3 |',
      '| 4 | 90% working weight | 1 |',
      '',
      'Then begin your working sets.',
    ].join('\n'),
    level: 'beginner' as const,
    readTimeMinutes: 3,
  },
  {
    title: 'Choosing the Right Weight',
    slug: 'choosing-the-right-weight',
    body: [
      '# Choosing the Right Weight',
      '',
      '## The RIR Method',
      '',
      '- **RIR 3**: You finish the set and could do 3 more reps',
      '- **RIR 2**: Could do 2 more',
      '- **RIR 1**: Could do 1 more (near failure)',
      '- **RIR 0**: You couldn\'t do another rep',
      '',
      '## Starting Out',
      '',
      'Start lighter than you think. You can always add weight next session.',
      '',
      '## Rule of Thumb',
      '',
      'Can\'t hit prescribed reps? Too heavy. Finishing with 4+ RIR when program says 2? Go heavier.',
    ].join('\n'),
    level: 'beginner' as const,
    readTimeMinutes: 4,
  },
]
